### ISSUE TITLE
Add Support for Swaps

### ISSUE THREAD

**Issue by hschickdevs** [hschickdevs/telegram-crypto-alerts#25]
User has requested the following:
- Track pancakeswap pair prices (similar to https://medium.com/@tokentools)
- They will be renting a BSC node, need to plug their RPC endpoint into the bot for retrieving data

**Comment by morpheusawait** [comment]
This is going to be amazing!

**Comment by hschickdevs** [comment]
Fetch data from: https://nodereal.io/api-marketplace/pancakeswap-graphql

**Comment by hschickdevs** [comment]
This has been moved to a dedicated repository (bot) where only decentralized exchanges will be tracked.

Work in progress: https://github.com/hschickdevs/Telegram-DeFi-Price-Alerts
