### ISSUE TITLE
Does it monitor and alert automatically? 

### ISSUE THREAD

**Issue by Mo7mud** [hschickdevs/telegram-crypto-alerts#32]
Does the bot monitor indicators and send alerts automatically or I need to monitor them by myself and send alerts to  users?
I couldn't get it from the documentation.
Thank you.

**Comment by hschickdevs** [comment]
Hello, when you create new alerts via the Telegram interface, the bot will automatically check the indicators and send an alert to Telegram when the alert condition is satisfied.
